---
# proxmox and proxmox_kvm options
api_user: 'root@pam'
api_password: '{{ vault_api_password }}'
api_host: '192.168.1.112'
defaults:
  vm_template: 'UbuntuCloud'
  node: 'proxmox1'
  target: 'proxmox2'
  pubkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  nameserver: '192.168.1.254'
  vmid: '999'
  net0: 'virtio,bridge=vmbr0,firewall=1'
  password: '{{ vault_testkube_password }}'
  nameservers: 
    - 192.168.1.254
    - 1.1.1.1
    - 8.8.8.8

cts:
  kube1:
    newid: '201'
    hostname: 'testkube1.longhorse.local'
    name: 'testkube1'
    ip: 192.168.1.211
  kube2:
    newid: '202'
    hostname: 'testkube2.longhorse.local'
    name: 'testkube2'
    ip: 192.168.1.212
  kube3:
    newid: '203'
    hostname: 'testkube3.longhorse.local'
    name: 'testkube3'
    ip: 192.168.1.213
  netapps:
    newid: '102'
    hostname: 'netapps.longhorse.local'
    name: 'netapps'
    ip: 192.168.1.102
