---
# creates and starts containers from container vars with host vars defaults
- name: remove virtual machines from test kube environment

  hosts: proxmox1
  gather_facts: false

  tasks:
    - name: stop testkube vms
      tags: proxmox, create, deploy
      proxmox_kvm:
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        name: '{{ item.value.name }}'
        node: '{{ item.value.node | default(defaults.node) }}'
        state: stopped
      with_dict: "{{ cts }}"
      loop_control:
        pause: 2

    - name: sleep
      pause:
        seconds: 10

    - name: stop testkube vms
      tags: proxmox, create, deploy
      proxmox_kvm:
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        name: '{{ item.value.name }}'
        node: '{{ item.value.node | default(defaults.node) }}'
        state: absent
      with_dict: "{{ cts }}"
      loop_control:
        pause: 2